### PR TITLE
Jakarta EE 10 Core Profile alignement

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Pull in Jakarta EE 10 Core Profile API

### CODE REVIEW

**Review by radcortez — CHANGES_REQUESTED** [review]
I think this PR should also update the version to 3.0-SNAPSHOT, so we don't accidentally release this with the 2.x version

**Comment by Emily-Jiang** [comment]
@radcortez I was going to update it when doing the Jenkins build. Anyway, I can update it here.

**Comment by Emily-Jiang** [comment]
@radcortez I have done the update. Please check to see whether you have any other comments.

**Comment by JanWesterkamp-iJUG** [comment]
@Emily-Jiang and @radcortez, I created an issue to discuss additional changes for the 3.0 release I would like to add in it: https://github.com/eclipse/microprofile-parent/issues/63

**Review by radcortez — APPROVED** [review]

**Pull request merged**
